#!/usr/bin/env bash
# Download the full dependency closure as wheels for offline install. Run ONCE while online,
# on the SAME OS/arch as the air-gapped laptop (macOS arm64, or manylinux x86_64), with
# Python 3.11 active. Writes vendor/wheels/ + requirements-lock.txt.
#
# Offline install later:
#   pip install --no-index --find-links vendor/wheels -r requirements-lock.txt
set -euo pipefail

cd "$(dirname "$0")/.."
WHEEL_DIR="vendor/wheels"
LOCK="requirements-lock.txt"
PYBIN="${PYTHON:-python3.11}"

if ! "$PYBIN" -c 'import sys; assert sys.version_info[:2]==(3,11)' 2>/dev/null; then
  echo "error: \$PYTHON must point at a Python 3.11 interpreter (got: $PYBIN)." >&2
  echo "       uv python install 3.11  &&  PYTHON=\$(uv python find 3.11) $0" >&2
  exit 1
fi

mkdir -p "$WHEEL_DIR"

# Resolve the closure from requirements.txt (runtime) + the packaging tools we need offline.
if command -v uv >/dev/null 2>&1; then
  DL=(uv pip download)
else
  DL=("$PYBIN" -m pip download)
fi

echo "==> resolving + downloading the runtime closure into $WHEEL_DIR"
"${DL[@]}" \
  --python-version 3.11 \
  --dest "$WHEEL_DIR" \
  -r requirements.txt \
  pip setuptools wheel

# Platform-specific wheels that MUST match the target laptop (not pure-python):
#   ctranslate2, onnxruntime, av, pyarrow, pymupdf, numpy, lxml, Pillow, psutil,
#   piper-tts / piper-phonemize. `pip download` above already picked the right ones for
#   THIS machine's platform tag — run this script on the target platform.
echo "==> also fetching piper-tts (TTS CLI, invoked as a subprocess, never imported)"
"${DL[@]}" --python-version 3.11 --dest "$WHEEL_DIR" piper-tts

echo "==> writing $LOCK from the downloaded wheel set"
"$PYBIN" - "$WHEEL_DIR" "$LOCK" <<'PY'
import sys, pathlib, re
wheel_dir, lock = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
seen = {}
for whl in sorted(wheel_dir.glob("*.whl")):
    name, version = whl.name.split("-")[:2]
    seen[re.sub(r"[-_.]+", "-", name).lower()] = version
for tgz in sorted(wheel_dir.glob("*.tar.gz")):
    stem = tgz.name[:-7]
    name, _, version = stem.rpartition("-")
    seen.setdefault(re.sub(r"[-_.]+", "-", name).lower(), version)
lock.write_text(
    "# Generated by scripts/vendor_wheels.sh — Python 3.11, offline install set.\n"
    "# pip install --no-index --find-links vendor/wheels -r requirements-lock.txt\n"
    + "".join(f"{n}=={v}\n" for n, v in sorted(seen.items()))
)
print(f"{len(seen)} pinned packages -> {lock}")
PY

echo
echo "vendored $(ls "$WHEEL_DIR" | wc -l | tr -d ' ') files into $WHEEL_DIR"
echo "commit vendor/wheels/ and $LOCK, then the laptop can install with no network:"
echo "  pip install --no-index --find-links vendor/wheels -r requirements-lock.txt"
